  # Setting DIALOG START
    - name: "Configure jitsi-meet package"
      debconf:
        name: "jitsi-videobridge2"
        question: "jitsi-videobridge/jvb-hostname"
        vtype: "string"
        value: "js.quersys.com"

    - name: "Configure jitsi-meet package"
      debconf:
        name: "jitsi-meet-web-config"
        question: "jitsi-meet/cert-choice"
        vtype: "select"
        value: "I want to use my own certificate"

    - name: "Configure jitsi-meet package"
      debconf:
        name: "jitsi-meet-web-config"
        question: "cert-path-crt"
        vtype: "string"
        value: "etc/ssl/js.quersys.com.key"

    - name: "Configure jitsi-meet package"
      debconf:
        name: "jitsi-meet-web-config"
        question: "cert-path-key"
        vtype: "string"
        value: "/etc/ssl/js.quersys.com.crt"
  # Setting DIALOG end