    - name: Configuración Videobridge. Insert a line at the end of a file.
      lineinfile: 
        dest: /etc/jitsi/videobridge/sip-communicator.properties
        line: '{{ item }}'
      with_items:
        - 'org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=172.16.3.34'
        - 'org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=95.216.101.211'
