---
- hosts: jitsi
  become: true
  tasks:

    - name: Configuration prosody
      blockinfile:
        dest: /etc/jitsi/videobridge/sip-communicator.properties
        insertafter: EOF
        block: |
          org.jitsi.videobridge.xmpp.user.shard-3.HOSTNAME=js.quersys.com
          org.jitsi.videobridge.xmpp.user.shard-3.DOMAIN=auth.js.quersys.com
          org.jitsi.videobridge.xmpp.user.shard-3.USERNAME=jvb
          org.jitsi.videobridge.xmpp.user.shard-3.PASSWORD=CKheKSyc
          org.jitsi.videobridge.xmpp.user.shard-3.MUC_JIDS=JvbBrewery@internal.auth.js.quersys.com
          org.jitsi.videobridge.xmpp.user.shard-3.MUC_NICKNAME=jvb2
          org.jitsi.videobridge.xmpp.user.shard-3.DISABLE_TCP_HARVESTER=true
          org.jitsi.videobridge.xmpp.user.shard-3.DISABLE_CERTIFICATE_VERIFICATION=true
          org.jitsi.videobridge.xmpp.user.shard-3.COLIBRI_WS_DOMAIN=js.quersys.com

    # - lineinfile:
    #     dest: /etc/jitsi/videobridge/sip-communicator.properties
    #     state: absent
    #     regexp: "# BEGIN ANSIBLE MANAGED BLOCK"

    # - lineinfile:
    #     dest: /etc/jitsi/videobridge/sip-communicator.properties
    #     state: absent
    #     regexp: "# END ANSIBLE MANAGED BLOCK"

    - replace:
        path: /etc/jitsi/videobridge/sip-communicator.properties
        regexp: "# BEGIN ANSIBLE MANAGED BLOCK"
        replace: '#'

    - replace:
        path: /etc/jitsi/videobridge/sip-communicator.properties
        regexp: "# END ANSIBLE MANAGED BLOCK"
        replace: '#'
